version: "3"

services:
  app:
    env_file: .env
    environment:
      - NODE_ENV=production
    ports: 
      - "8080:3000"
    build:
      context: ./
      dockerfile: ./Dockerfiles/node/Dockerfile
